// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------------- //
// hub75_data_rgb888 //
// ----------------- //

#define hub75_data_rgb888_wrap_target 0
#define hub75_data_rgb888_wrap 15

#define hub75_data_rgb888_offset_entry_point 0u
#define hub75_data_rgb888_offset_shift0 0u
#define hub75_data_rgb888_offset_shift1 7u

static const uint16_t hub75_data_rgb888_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0     
    0x40e1, //  1: in     osr, 1          side 0     
    0x6068, //  2: out    null, 8         side 0     
    0x40e1, //  3: in     osr, 1          side 0     
    0x6068, //  4: out    null, 8         side 0     
    0x40e1, //  5: in     osr, 1          side 0     
    0x6060, //  6: out    null, 32        side 0     
    0x80a0, //  7: pull   block           side 0     
    0x50e1, //  8: in     osr, 1          side 1     
    0x7068, //  9: out    null, 8         side 1     
    0x50e1, // 10: in     osr, 1          side 1     
    0x7068, // 11: out    null, 8         side 1     
    0x50e1, // 12: in     osr, 1          side 1     
    0x7060, // 13: out    null, 32        side 1     
    0x507a, // 14: in     null, 26        side 1     
    0xb016, // 15: mov    pins, ::isr     side 1     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program hub75_data_rgb888_program = {
    .instructions = hub75_data_rgb888_program_instructions,
    .length = 16,
    .origin = -1,
};

static inline pio_sm_config hub75_data_rgb888_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + hub75_data_rgb888_wrap_target, offset + hub75_data_rgb888_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif
